name: 'AI-CI-Example'

on:
  push:
    branches:
      - main
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Unit Test
        run: make unit-test

      - name: Build
        run: |-
          make build

      - name: Terraform Init
        id: tf_init
        run: cd terraform && terraform init

      - name: Terraform Validate
        id: tf_validate
        run: |-
          make validate

      - name: Deploy
        run: |-
          make deploy

      - name: Interface Test
        run: |-
          make interface-test
