name: 'Deploy albumsvr to AWS EC2'

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  provision-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Unit Test
        run: make unit-test

      - name: Build
        run: make build

      - name: Setup Node Version
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: '${{ secrets.AWS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_KEY_SECRET }}'
          aws-region: ap-southeast-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Apply
        id: apply
        run: |-
          cd terraform/aws/
          terraform init
          terraform validate
          terraform plan
          terraform apply -auto-approve
        env:
          TF_VAR_aws_pem: ${{ secrets.AWS_PEM }}
          TF_VAR_github_action_workspace: ${{ github.workspace }}
